name: Docker Image CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - id: semver
      uses: SOLIDSoftworks/semver-tags@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        default-version: '1.0.0'
        previous-major-version: 1
        previous-minor-version: 0
        create-release: true

    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src --packages ./packages
    - name: Build solution
      run: dotnet build src --no-restore -c Release -p:Version=${{ steps.semver.outputs.core-version }}
    - name: dotnet publish
      run: dotnet publish src -p:Version=${{ steps.semver.outputs.core-version }} --no-build -c Release -o ./publish
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: ./src/TempMonitor/Dockerfile
        # List of metadata for an image
        platforms: linux/arm64        
        push: true
        tags: ghcr.io/gislikonrad/temp-monitor:${{ steps.semver.outputs.core-version }}




